services:
  server:
    build:
      context: .
      target: prod
      dockerfile: dockerfile
    container_name: ocean-prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - ocean-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
