services:
  api:
    build:
      context: .
      target: development
      dockerfile: dockerfile
    container_name: api-prod
    restart: unless-stopped
    env_file: .env.prod
    networks:
      - ocean-net
    # === Configs for production environment ===
    depends_on:
      postgres: # Wait for the database to be healthy
        condition: service_healthy
    healthcheck: # Use curl to check if the application is healthy
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    
  postgres:
    extends:
      service: postgres
      file: compose.base.yml
    container_name: postgres-prod
    restart: unless-stopped
    env_file: .env.prod
