FROM oven/bun:1.3.5-alpine AS base
WORKDIR /usr/src/app

# === Dependencies Stage ===
FROM base AS dependencies
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

# === Development Stage ===
FROM dependencies AS development
COPY . .
USER bun

EXPOSE 3000
ENTRYPOINT [ "bun", "run", "start" ]

## === Building Stage ===
FROM dependencies AS building
COPY . .
RUN bun run build

# === Production Stage ===
FROM alpine:3.23 AS production
WORKDIR /usr/src/app

RUN apk add --no-cache libstdc++ libgcc && \
  addgroup -S oceangroup && adduser -S oceanuser -G oceangroup

COPY --from=building --chown=oceanuser:oceangroup /usr/src/app/ocean .
USER oceanuser

EXPOSE 3000
ENTRYPOINT [ "./ocean" ]
