FROM oven/bun:1.3.5-alpine AS base
WORKDIR /usr/temp
COPY package.json bun.lock ./

FROM base AS dev
RUN bun install --frozen-lockfile

COPY . .
USER bun

EXPOSE 3000
ENTRYPOINT [ "bun", "run", "start" ]

FROM base AS build
RUN bun install --frozen-lockfile --production

COPY . .
RUN bun run build

FROM alpine:3.23 AS prod
WORKDIR /usr/src/app

RUN apk add --no-cache curl && \
  addgroup -S oceangroup && \
  adduser -S oceanuser -G oceangroup

COPY --from=build /usr/temp/ocean .
RUN chown -R oceanuser:oceangroup /usr/src/app

USER oceanuser
EXPOSE 3000
ENTRYPOINT [ "./ocean" ]
